# Adapted from https://www.scala-sbt.org/1.x/docs/GitHub-Actions-with-sbt.html
name: CI
on:
  pull_request:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
      - name: Compile runtime class
        run: (cd runtime_src && make)
      - name: Build and Test
        run: sbt -v +test